#!/usr/bin/env php
<?php

declare(strict_types=1);

$tasks = [
    'init' => __DIR__ . '/tools/init.php',
    'create-test-user' => __DIR__ . '/tools/create-test-user.php',
    'switch-license' => __DIR__ . '/tools/switch-license.php',
    'cleanup-template' => __DIR__ . '/tools/cleanup-template.php',
];

if ($argc < 2 || in_array($argv[1], ['-h', '--help', 'help'], true)) {
    usage($tasks);
}

$task = $argv[1];

if (!array_key_exists($task, $tasks)) {
    usage($tasks, "Unknown task: {$task}");
}

$script = $tasks[$task];
$args = array_slice($argv, 2);

$command = escapeshellarg(PHP_BINARY) . ' ' . escapeshellarg($script);
foreach ($args as $arg) {
    $command .= ' ' . escapeshellarg($arg);
}

passthru($command, $exitCode);
exit((int) $exitCode);

function usage(array $tasks, ?string $message = null): void
{
    if ($message !== null) {
        fwrite(STDERR, $message . PHP_EOL);
    }

    $list = implode(PHP_EOL . '  - ', array_keys($tasks));

    fwrite(
        STDERR,
        <<<TXT
Usage: php task <command> [args...]

Available commands:
  - {$list}

TXT
    );

    exit(1);
}
