#!/usr/bin/env python3
"""Derive the Writer's foreground-only COLR font without changing its geometry."""

import argparse
import base64
import copy
import io
from pathlib import Path

from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "assets/fonts/hidden-characters.woff2"
FONT = ROOT / "assets/fonts/hidden-characters-writer.woff2"
CSS = ROOT / "src/styles/writer-font.css"


def generate():
    font = TTFont(SOURCE, recalcTimestamp=False)
    if font["COLR"].version != 0:
        raise ValueError("Expected the source font's COLR v0 layer model")
    unchanged = {
        tag: font.getTableData(tag)
        for tag in font.keys()[1:]
        if tag not in {"COLR", "head"}
    }
    head = font.getTableData("head")

    # Keep all outlines, advances and variation data intact. Only the COLR
    # references change: omit the foreground guards and use text foreground
    # (0xFFFF) for the visible marker instead of the fixed palette entry.
    for glyph, layers in font["COLR"].ColorLayers.items():
        markers = [copy.copy(layer) for layer in layers if layer.colorID == 0]
        guards = [layer for layer in layers if layer.colorID == 0xFFFF]
        if len(markers) != 1 or len(guards) != 1 or len(layers) != 2:
            raise ValueError(f"Unexpected marker/guard layers for {glyph}")
        markers[0].colorID = 0xFFFF
        font["COLR"].ColorLayers[glyph] = markers

    output = io.BytesIO()
    font.save(output)
    data = output.getvalue()
    result = TTFont(io.BytesIO(data), recalcTimestamp=False)
    result_head = result.getTableData("head")
    if result_head[:8] + result_head[12:] != head[:8] + head[12:]:
        raise ValueError("Writer generation changed head beyond its checksum")
    for tag, original in unchanged.items():
        if result.getTableData(tag) != original:
            raise ValueError(f"Writer generation unexpectedly changed {tag}")
    encoded = base64.b64encode(data).decode("ascii")
    css = f'''/* Generated by tools/build-writer-font.py; do not edit by hand. */
@font-face {{
  font-display: swap;
  font-family: "hidden-characters-writer";
  font-style: normal;
  font-weight: normal;
  src: url("data:font/woff2;base64,{encoded}") format("woff2");
  unicode-range: U+0020, U+00A0, U+2000-200B, U+202F, U+205F, U+E000-E004;
}}
'''
    return {FONT: data, CSS: css.encode("utf-8")}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify without writing files")
    args = parser.parse_args()
    for path, expected in generate().items():
        if args.check:
            if not path.exists() or path.read_bytes() != expected:
                raise SystemExit(f"Stale {path.relative_to(ROOT)}; run pnpm fonts:build")
        else:
            path.write_bytes(expected)
    print("Writer font and embedded CSS are current." if args.check else "Writer font and embedded CSS generated.")


if __name__ == "__main__":
    main()
